services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: joshludolf/awesome-iguanas:latest
    container_name: awesome-iguanas
    ports:
      - "443:443"     # Map host port 443 to container port 443 for HTTPS
      - "80:80"       # Map host port 80 to container port 80 for HTTP
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "awesome-iguanas.com:127.0.0.1"
    environment:
      - VITE_NEO4J_URI=${NEO4J_URI:-bolt://127.0.0.1:7687}
      - VITE_NEO4J_USER=${NEO4J_USER:-neo4j}
      - VITE_NEO4J_PASSWORD=${NEO4J_PASSWORD:-jaguarai}
      - VITE_OLLAMA_API_URL=${OLLAMA_API_URL:-http://127.0.1:11434}
      - VITE_OLLAMA_MODEL=${OLLAMA_MODEL:-deepseek-r1:8b}
      - VITE_GITHUB_TOKEN=${GITHUB_TOKEN:-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}
      - VITE_NIST_TOKEN=${NIST_TOKEN:-6316e397-064c-42de-8fd0-839574fe2e9e}
    volumes:
      - ./frontend:/app
      - /app/node_modules
